linters-settings:
  misspell:
    locale: US
linters:
  disable-all: true
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - gosimple
    - govet
    - revive
    - ineffassign
    - vet
    - unused
    - misspell
    - whitespace
    - gosec
run:
  timeout: 5m
  go: '1.18'
  skip-dirs:
    - script
